In [1]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
import random
import matplotlib.pyplot as plt

In [2]:
def get_item(p):  # Function of generation random bits array with lenth 8
    noise = np.random.rand(8) < p
    binary_string = ''.join(str(int(b)) for b in noise)
    result_integer = int(binary_string, 2)
    return result_integer

In [3]:
class DenoisingAutoencoder(keras.Model):
    def __init__(self, latent_dim):
        super(DenoisingAutoencoder, self).__init__()
        self.encoder = keras.Sequential([
            layers.Input(shape=(input_dim,)),  # Input layer
            layers.Dense(128, activation='relu'),  # Hidden layer
            layers.Dense(latent_dim, activation='relu')  # Latent space
        ])
        self.decoder = keras.Sequential([
            layers.Dense(128, activation='relu'),  # Hidden layer
            layers.Dense(input_dim, activation='sigmoid')  # Output layer
        ])

    def call(self, x):
        p = 0.03
        noise = np.array([get_item(p) for _ in range(128)])  # Add noise
        x_noisy = x ^ noise  # Create noisy input
        encoded = self.encoder(x_noisy)  # Encode noisy input
        decoded = self.decoder(encoded)  # Decode back to original
        return decoded

In [5]:
input_dim = 64
data = np.array([[random.getrandbits(8) for _ in range(64)] for _ in range(1000000)])

In [7]:
latent_dim = 128  # Dimension of latent space
autoencoder = DenoisingAutoencoder(latent_dim)

p = 0.03
noise = np.array([[get_item(p) for _ in range(64)] for _ in range(1000000)])  # Add noise
x_noisy = data ^ noise  # Create noisy input

In [ ]:
autoencoder.compile(optimizer='adam', loss='mean_squared_error')
autoencoder.fit(x_noisy, data, epochs=10, batch_size=32)  # Train on original data

In [29]:
encoded_message = autoencoder.encoder(np.array([[random.getrandbits(8) for _ in range(8)]]))
print(encoded_message)

tf.Tensor(
[[ 0.          0.          0.         38.01832     0.          0.
   0.          0.          0.         65.358154    0.          0.
   0.          0.         53.17025    22.743805   23.683601    0.
   0.          0.          0.16200265  0.          0.          0.
   0.          0.         12.505103   12.189944    0.         39.546333
   0.         29.28175    41.00837     0.         38.319565   58.25923
  40.353725   67.75286    59.023037   19.155825    1.2221249   0.
   0.          0.          0.          0.          7.39626    21.683966
   8.262469    4.485443   19.286865   17.894773    0.         67.36286
  59.623394    0.         54.371983    0.          0.         19.358458
  15.442731    0.          0.          0.         53.45756     0.
  38.509445   23.461264    0.         41.266895    0.          0.
   0.         92.462456   53.876232   36.725883    3.075022    0.
   0.         28.072054   33.647823   50.543972   22.996023    0.
  21.434927   35.445507   35.52179   

In [30]:
latent_dim = 64  # Dimension of latent space
autoencoder = DenoisingAutoencoder(latent_dim)

autoencoder.compile(optimizer='adam', loss='mean_squared_error')
autoencoder.fit(data, data, epochs=10, batch_size=32)  # Train on original data

Epoch 1/10
31250/31250 ━━━━━━━━━━━━━━━━━━━━ 18s 549us/step - loss: 21487.0938
Epoch 2/10
31250/31250 ━━━━━━━━━━━━━━━━━━━━ 18s 590us/step - loss: 21475.0898
Epoch 3/10
31250/31250 ━━━━━━━━━━━━━━━━━━━━ 19s 618us/step - loss: 21478.4258
Epoch 4/10
31250/31250 ━━━━━━━━━━━━━━━━━━━━ 19s 620us/step - loss: 21470.7109
Epoch 5/10
31250/31250 ━━━━━━━━━━━━━━━━━━━━ 20s 648us/step - loss: 21466.2031
Epoch 6/10
31250/31250 ━━━━━━━━━━━━━━━━━━━━ 20s 635us/step - loss: 21475.6367
Epoch 7/10
31250/31250 ━━━━━━━━━━━━━━━━━━━━ 19s 611us/step - loss: 21472.3066
Epoch 8/10
31250/31250 ━━━━━━━━━━━━━━━━━━━━ 19s 621us/step - loss: 21469.9785
Epoch 9/10
31250/31250 ━━━━━━━━━━━━━━━━━━━━ 20s 637us/step - loss: 21474.0703
Epoch 10/10
31250/31250 ━━━━━━━━━━━━━━━━━━━━ 21s 657us/step - loss: 21480.0156


In [34]:
encoded_message = autoencoder.encoder(np.array([[random.getrandbits(8) for _ in range(8)]]))
print(encoded_message)

tf.Tensor(
[[  0.         0.         0.         0.         0.         0.
   18.547686   0.         0.        35.72628   36.05042   76.74711
   51.483913  43.860306  73.00447   49.862114  29.501163  70.95864
    0.         0.         0.        37.572968   0.        17.283861
   84.7498    61.69039    0.        50.976784  71.22127    0.
    0.         0.         0.         0.        30.026886   0.
    0.         0.         0.        86.3741   104.68269   22.669992
  119.031746  65.783264  58.60173   40.23284   43.508728  70.19675
   35.544636   0.        37.384514  53.48927   53.089794   4.912781
    0.        62.884056   0.         0.         0.        81.438644
    0.        52.31676    0.         0.      ]], shape=(1, 64), dtype=float32)


In [35]:
# Decoding the encoded message
decoded_message = autoencoder.decoder(encoded_message)
print(decoded_message)

tf.Tensor([[1. 1. 1. 1. 1. 1. 1. 1.]], shape=(1, 8), dtype=float32)


Loss doesn't falling

In [40]:
latent_dim = 128  # Dimension of latent space
autoencoder = DenoisingAutoencoder(latent_dim)

autoencoder.compile(optimizer='adam', loss='mean_squared_error')
autoencoder.fit(data, data, epochs=1, batch_size=32)  # Train on original data

31250/31250 ━━━━━━━━━━━━━━━━━━━━ 22s 703us/step - loss: 21483.0020
